apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: walmart-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: ghcr.io/marckmorris/pm-stakeholder-qa-langchain:latest
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          envFrom:
            - secretRef:
                name: app-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: walmart-demo
spec:
  selector:
    app: app
  ports:
    - port: 80
      targetPort: 8000
