name: CI (pm-okr-advisor-langchain only)
on:
  push:
    branches: [ "main" ]
  pull_request:
    paths:
      - "pm-okr-advisor-langchain/**"
      - ".github/workflows/ci-pm-okr.yml"
jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: pm-okr-advisor-langchain
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install pytest
      - run: pytest -q
