name: CI (retail-assortment-agent-langgraph only)

on:
  push:
    branches: [ "main" ]
  pull_request:
    paths:
      - "retail-assortment-agent-langgraph/**"
      - ".github/workflows/ci-retail-assortment.yml"

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: retail-assortment-agent-langgraph
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate project structure
        run: |
          test -f requirements.txt
          test -f app/main.py
          test -f tests/test_health.py

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install pytest

      - name: Smoke import
        run: |
          python - << 'PY'
          import importlib.util
          spec = importlib.util.spec_from_file_location("app.main", "app/main.py")
          m = importlib.util.module_from_spec(spec)
          spec.loader.exec_module(m)
          assert hasattr(m, "app"), "No FastAPI app in app/main.py"
          print("Import OK")
          PY

      - name: Run tests
        run: pytest -q
